#!/bin/sh

uci -q batch <<-EOF
	set system.@system[0].timezone='UTC+7'
	set system.@system[0].zonename='Asia/Jakarta'

	delete system.ntp.server
	add_list system.ntp.server='ntp.bmkg.go.id'
	add_list system.ntp.server='jam.bmkg.go.id'
	add_list system.ntp.server='time.bmkg.go.id'
	add_list system.ntp.server='time.nist.gov'
EOF
uci commit system

sed -i 's,downloads.immortalwrt.org,mirrors.vsean.net/openwrt,g' /etc/opkg/distfeeds.conf

exit 0
